### PR TITLE
space around AS token

### PR DESCRIPTION
**Pull request by btakita**
Fixes https://github.com/tomblachut/svelte-intellij/issues/20

### CODE REVIEW

**Comment by unlocomqx** [comment]
I think it should be fixed in Svelte.flex file

**Comment by tiatin** [comment]
@btakita - I think better way would be updating flexer: `\s+"as"\s+` under `<SVELTE_TAG, SVELTE_TAG_PAREN_AWARE>` states.

**Comment by tomblachut** [comment]
BNF files don't deal with whitespaces. This would break other features of IDE.

**Comment by tomblachut** [comment]
Superseded by #18

**Pull request closed without merging**
