### PR TITLE
Merged abstract syntax tree

### LINKED ISSUE #19: Emmet is not working as expected
Can this be because of this plugin? I'm using Goland.

I haven't found out when exaclty it doesn't work. It never works inside another tag. Sometimes it doesn't even work on the root level.

Changing the File type of `.svelte` files back to HTML makes everything work as expected again.

emmet

### PR DESCRIPTION
**Pull request by tomblachut**
I'm really happy about this PR number.

Resolves #19 

TODO:
- [x] Parser edge cases
- [x] Formatting
- [x] Commenter
- [x] Folding
- [x] Brace typing
- [x] Tests

### CODE REVIEW

**Comment by anstarovoyt** [comment]
Why did you change SvelteHtmlFile from HtmlFileImpl to JSFileImpl? I believe the solution with HtmlFile is more "correct". Also, it works in the same way for e.g. Vue and the solution looks viable.

**Comment by anstarovoyt** [comment]
as far as I can see tests don't work. It can be fixed by adding missing dependency 'platform-images'.
```
plugins = ['JavaScriptLanguage', 'CSS', 'platform-images' , 'PsiViewer:201.3803.71-EAP-SNAPSHOT.1']
```

**Comment by tomblachut** [comment]
@anstarovoyt interesting, thanks. Can you point me to some resource what this plugin is responsible for?

**Comment by anstarovoyt** [comment]
> interesting, thanks. Can you point me to some resource what this plugin is responsible for?

CSS depends on 'platform-images' and the 'platform-images' is an "internal" plugin. It isn't obvious and it will be fixed in the Gradle plugin in the future.

**Comment by anstarovoyt** [comment]
@tomblachut  Why did you change SvelteHtmlFile super class from HtmlFileImpl to JSFileImpl? I believe the solution with HtmlFile is more "correct". Also, it works in the same way for e.g. Vue and the solution looks viable.

**Comment by tomblachut** [comment]
Fortunately gradle plugin was released before I've got around to fixing tests and they work after upgrading it (besides parser test, need to debug NPE :))

> Why did you change SvelteHtmlFile super class from HtmlFileImpl to JSFileImpl? I believe the solution with HtmlFile is more "correct". Also, it works in the same way for e.g. Vue and the solution looks viable.

Are you on the newest branch? Sorry about the confusion, this PR consists of a lot of experimentation on my side, I've dropped that commit because it did more harm than good.

Still, going forward after this PR I'll need some solution to the problem of `EMBEDDED_CONTENT_MODULE` token. More details here: https://www.notion.so/State-of-svelte-intellij-April-May-2020-0d1b551e9972436194599f070328900f (please scroll to "Reactive labels" section). I'd rather not reimplement whole JS static analysis code. Vue unfortunately only has custom parsing in expressions, script tag uses built in ES6, so the use case it not the same.

**Comment by anstarovoyt** [comment]
> to the problem of EMBEDDED_CONTENT_MODULE token

@tomblachut sorry for that. Looks like this API is very limited. I can fix it for 2020.1.2 (introduce an interface for export scope / embedded block owners). What do you think is it ok, or we need to search for a solution that also works for 2019.3 / 2020.1.1?

**Comment by tomblachut** [comment]
@tomblachut "interface for export scope / embedded block owners" would be great. 

My experience is limited here, I'd like to avoid dropping support for 2019 but I imagine other solution would be cumbersome to implement and my time is limited so I'll take what life gives me :) Unfortunetly Plugin Marketplace does not provide usage statistics broken down by IDE version so I don't know how many users use 2020.

BTW how does fallback license work exactly. If i have a fallback license for 2020.1.1 can i get patch release like mentioned 2020.1.2 or is it locked to exactly  2020.1.1?

**Comment by anstarovoyt** [comment]
>f i have a fallback license for 2020.1.1 can i get patch release like mentioned 2020.1.2 or is it locked to exactly 2020.1.1?

Path-releases are always included in the fallback license.

I am going to implement proper interfaces on the JS plugin side.

**Comment by tomblachut** [comment]
@anstarovoyt great, thanks

**Comment by shirotech** [comment]
@tomblachut have a small regression as outlined in #116

**Comment by tomblachut** [comment]
@anstarovoyt looks neat. I'd like to merge this PR and release it as last one for 2019, then switch supported version range to 2020 and start working on reactive labels and TS.

As for Merged AST I don't know if I'll ever finish it 😧  I need to once again rewrite parser because I've noticed unbalanced markers edge cases. Good news is that I finally have some free time this week.

Also, your tests already proved useful.

I have a question related to that, **what's the correct way to detect Svelte context?** Previously I've been checking e.g. 
```
scope.containingFile.viewProvider is SvelteFileViewProvider
```
but with this PR it stopped working at least for `SvelteTagProvider.addTagNameVariants` - it's `SingleRootFileViewProvider` there. IDK how to debug that but maybe I don't need to because it should be checked otherwise anyway?

Vue is doing something Like that:
```
  val file = psiFile.originalFile.virtualFile
  if ((file != null && file.fileType == VueFileType.INSTANCE) || (file == null && psiFile.language == VueLanguage.INSTANCE)) {}
```
Seems complex for I think basic verification

**Comment by tomblachut** [comment]
@anstarovoyt btw slightly offtopic, what happened with `ES6ModulesDependenciesInspection` in 2020.2?

**Comment by anstarovoyt** [comment]
@tomblachut 

>what's the correct way to detect Svelte context?

If you still have SvelteFile it can be 
```
scope.containingFile instanceof SvelteFile
```
otherwise, it should be the same solution like in vue

>btw slightly offtopic, what happened with ES6ModulesDependenciesInspection in 2020.2?

we had to unify the inspection with another similar mechanism in ts files. Now the import fixes are provided using the new extension point
```
com.intellij.lang.javascript.validation.JSUnresolvedReferenceErrorUpdater
```

**Comment by tomblachut** [comment]
@anstarovoyt `SvelteFileViewProvider` can be deleted without performance impact, right? The only thing it does now is hardcode `SvelteHTMLLanguage.INSTANCE`

**Comment by anstarovoyt** [comment]
>SvelteFileViewProvider can be deleted without performance impact, right? The only thing it does now is hardcode SvelteHTMLLanguage.INSTANCE

if the file isn't composite (aka language + template language) yes, it is ok. Almost all our languages use the default view provider implementation

**Comment by tomblachut** [comment]
It isn't anymore, there were many bugs around outer language boundaries, that's why I decided to rewrite core code. Thanks, I'm going to remove custom provider then.

**Comment by tomblachut** [comment]
Defo longest living branch in my whole career 😅

**Comment by anstarovoyt** [comment]
@tomblachut awesome!

**Pull request merged**
