### PR TITLE
support for webstorm

### PR DESCRIPTION
**Pull request by mallowigi**
Support for Webstorm and Co.

### CODE REVIEW

**Comment by mallowigi** [comment]
is this project dead or what

**Comment by tomblachut** [comment]
No it isn't. Thanks for your contribution! I just have personal things to care for. I'll try to merge it shortly

**Comment by mallowigi** [comment]
bump

**Comment by nightwolfz** [comment]
@mallowigi Thanks man, I'm using your fork atm

**Comment by btakita** [comment]
How do you create a build & use this branch?

**Comment by tomblachut** [comment]
Hi! Ok that was a long 'shortly' from me. Sorry.

I don't understand fully purpose of this PR. Current version works in latest WebStorm. You mean to support 2019.2 EAP and future ones?

**Comment by tomblachut** [comment]
Connected with #23 and fixed in https://github.com/tomblachut/svelte-intellij/commit/04a0b38ffcd0fcecbe1da7a31dc66c22e9666ff4

**Pull request closed without merging**
