### PR TITLE
inject Svelte in attribute value

### PR DESCRIPTION
**Pull request by unlocomqx**
I moved the injection from LanguageInjection to the MultiHostInjector
I also used only `SvelteLanguage` for the injection to let `SvelteCodeInjectionVisitor` do the rest
I couldn't do the same for attribute names, it seems unsupported as far as I tested

### CODE REVIEW

**Comment by tomblachut** [comment]
> I couldn't do the same for attribute names

You mean shorthand props like `<Foo {name}>`?

**Comment by unlocomqx** [comment]
Yeah <Foo `{name}`> and also use:`function` transition:`fade` etc
I checked other similar plugins, no one seems to do it, even angular directives
Attribute name are not a valid injection host as far as I understood

**Comment by tomblachut** [comment]
Okay I finally figured out #50 which gives me better outlook on the next steps. I think that this PR needs to be closed (but let's leave it open for now). 

Inside that PR there's a comment with a roadmap and since you put significant amount of work into this plugin I thought this might interest you.

**Comment by unlocomqx** [comment]
Brilliant! I'd be glad if I contributed even with a good idea :smile: 
I'll close this PR because the multi injector was removed. A simpler way to do this could be by using `<languageInjector`

**Comment by tomblachut** [comment]
I think it's better to lazily parse attribute value

**Comment by unlocomqx** [comment]
Yes, I just saw the comment in #50 
Cheers!

**Pull request closed without merging**
